id: P4545D116
initial_creation_type: ocr
source_metadata:
  volumes:
    3ff3bfb4470f40debd8ec28c3834ea7e:
      base_file: v013.txt
      image_group_id: I1PD95858
      title: དཔལ་གདན་བཞི་པའི་ཟབ་དོན་སྟོན་པ་ཤིང་གཅིག་གི་དཀའ་འགྲེལ།
      total_pages: 2043
      volume_number: 13
